# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-22 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='release_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.CharField(max_length=100)),
                ('svn_url', models.CharField(max_length=100)),
                ('added_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ws_name', models.CharField(max_length=100)),
                ('svn_url', models.CharField(max_length=100)),
                ('added_by', models.CharField(max_length=100)),
                ('add_date', models.DateField()),
                ('ws_path', models.CharField(max_length=100, null=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.release_list')),
            ],
        ),
    ]
